# Generated by Django 3.2.6 on 2021-08-20 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2021, 8, 20, 19, 7, 54, 763249, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
