# Generated by Django 3.2.6 on 2021-08-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210821_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_identities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
