# Generated by Django 3.2.6 on 2021-08-31 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_social_identities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmationToken',
        ),
    ]
