name: flake8

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip wheel
          pip install flake8
      - name: Run flake8
        run: flake8
